### ISSUE TITLE
Artisan can't be found when trying to migrate/seed before tests

### ISSUE THREAD

**Issue by gerob** [BenConstable/phpspec-laravel#28]
After 'vendor/bin/phpspec run` I get this error. Running artisan on the command line works fine.

```
[ReflectionException]
  Class artisan does not exist
```

My phpspec.yml

```
extensions:
    - PhpSpec\Laravel\Extension\LaravelExtension

laravel_extension:
    http_kernel_class: GerobLee\Http\Kernel
    migrate_db: true
#    seed_db: true

suites:
    main:
        namespace: GerobLee
        psr4_prefix: GerobLee
        src_path: app/
        spec_path: tests/

```

The tests all run fine until I add `migrate_db`.
