### ISSUE TITLE
Can't find spec test

### ISSUE THREAD

**Issue by Pedramrn** [BenConstable/phpspec-laravel#30]
Here is my phpspec.yml file

```
suites:
    main:
        namespace: App
        psr4_prefix: App
        src_path: app

    extensions:
        - PhpSpec\Laravel\Extension\LaravelExtension
```

I have one spec test in
```
root
   -spec
       -Moldels
             -UserSpec.php
```  

When I run phpsec nothing happens!!
```
0 specs
0 examples
0ms  
```
