### ISSUE TITLE
Class App\Console\Kernel does not exist

### ISSUE THREAD

**Issue by Shandur** [BenConstable/phpspec-laravel#45]
Hello. I have a problem: after installing of your extension and setting up in phpspec.yml I have an error "Class App\Console\Kernel does not exist" when run tests. My tests are located in Modules/User/Tests/Unit folder, not in the root tests folder. I ran tests from Modules/User folder.

Here is my phpspec.yml settings:
extensions:
  PhpSpec\Laravel\Extension\LaravelExtension:
    framework_path: "./../../../bootstrap/app.php"
    testing_environment: "testing"
formatter.name: pretty
suites:
  user_suite:
    namespace: Modules\User
    psr4_prefix: Modules\User
    spec_prefix: 'Tests\Unit'
    spec_path: .
    src_path: . 

[Screen here](http://joxi.ru/bmoJMOOUKjqlry)

**Comment by BenConstable** [comment]
As you're using a non-standard directory setup, I can't be sure what's causing the issue. To confirm, does your `App\Console\Kernel` class exist and are you able to run `php artisan list` without trouble?

Also, is your phpspec.yml file located in your application's root directory? If not, you should moved to the file to the root and then set the `spec_path` and `src_path` appropriately for each suite.

Finally, I believe your spec directory needs to be outside of your source directory. You should probably move your tests to `spec/Modules/User/` (or something similar). Your config file would then look like this:

```yml
extensions:
    PhpSpec\Laravel\Extension\LaravelExtension:
        testing_environment: "testing"
suites:
    user_suite:
        namespace: Modules\User
        psr4_prefix: Modules\User
        src_path: modules\User # this is a guess - set this as you see fit
        spec_path: spec/modules/User
```
